language: node_js
node_js:
- '4'
- stable
notifications:
  email: false
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/54f8a1e753f859f5ca1a
    on_start: never
    on_failure: change
deploy:
  provider: npm
  email: jimmy.aumard@gmail.com
  api_key:
    secure: hb+w/S5oaaZl1008yNr8tSezxunrXP9nmbrQkd5u2TJ6iV87bT+5BRX639lJW7QsK+mFnwr3q5sBxwm3NIxNXrtKtOM+d1Nv6Fi93c9DOfP6bbmiIuNMBVEHfGvdZdYb2j8O2jMfCpI1t4yMm5BxV1Ofrtg+DGsQnS4MtMbXidTFiluh93cS506Pv2VjKQf0ioV2+KzYVX4WrTOm81jXx1sXKomxPQtaMmFA9ZB6efaQs/d3isjT2F7gHl4GYT5eoLprs6Ht7COYBD0nKpbm9eN8pMIrt/YiQM+aMvVL/4Seghsm2SjPOJ9FZl2ui7jkvm+jp2XNsigT0r7+P0dVxmRrgl1GMzf46F8xdB6tEDVH4rQcTARzp9Uexq7mZov5/fpyYoHwFYDXJpDAgMYfvSr67GHBLjiAezMBKFlkEWzbdKudxazXag37lpXOQZ9V6WVWqT6o6Dbftz7ZMAk9DTAMPmLn39WX5tNUb2UY5pwbf5gbiG5xPrAxGFOal6I9E1v6ih38j2OVM1QilUdqg0VrUxi+gGKFMOTCNrQJpzjb1S4E/X8sfaiLHTMY3HR7K7o8FLFskMcY8wRXiYfLoZdVpzBt6l95IVJq3FfY57MLCjfHsAyskLe6b3+3iqtOTtQW6djPuEfjowuyCTou6Hvtjlt2cRrBfG5+jzyyfs8=
  on:
    tags: true
    repo: jaumard/trailpack-machinepack
    all_branches: true
    node: stable
